### ISSUE TITLE
I cant download all the map data

### ISSUE THREAD

**Issue by Internetuserin2024** [Slvr11/AIZombiesSupreme#1]
First of all thanks for uploading and hosting the mw3 version of your zombies mode I have played a few rounds
and overall had a good experience with random people playing with me. But sometimes the map switches and the Plutonium launcher doesnt load the new map thus crashing. I have downloaded your repository but cant figure out how to reinstall the map files to fix my problem. Maybe you can  post a quick text tutorial on how to install all map files.

Cheers mate

**Comment by Slvr11** [comment]
This repo is for the TeknoMW3 version of AIZombies. The PlutoIW5 repo will become public when the mod is ready for release.

But the issue you're having on Pluto is just the client's fault. AIZombies is a big mod and the client can't always handle it well. If you crash during loading then just rejoin. Pluto needs to fix mod support in general.
