### ISSUE TITLE
Server closes after start_map_rotate

### ISSUE THREAD

**Issue by SShattered** [Slvr11/AIZombiesSupreme#2]
I'm using latest TeknoMW3 and 1.4 patch

**Comment by Slvr11** [comment]
Turn off Auto Updates and/or Custom Gametype settings in the config.cfg file within `scripts/aizombies`. You PC does not support these features.

**Comment by SShattered** [comment]
It was my bad not reading the config file. Could you please add about this to readme? I think it might make people like me having less trouble :)

**Comment by SShattered** [comment]
It was my bad not reading the config file. Could you please add about this to readme? I think it might make people like me having less trouble :)
